[package]
name = "keycord"
description = "Browse and edit password stores"
authors = ["noobping <hello@noobping.dev>"]
version = "0.9.12"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/noobping/keycord"
repository = "https://github.com/noobping/keycord"

[features]
audit = []
default = []
docs = ["dep:pulldown-cmark"]
fidokey = ["dep:base64", "dep:fido2-rs", "dep:hmac", "dep:openssl"]
fidopin = ["dep:libfido2-sys"]
flatpak = ["docs", "audit", "smartcard", "logging", "passkey"]
hardwarekey = ["smartcard"]
logging = []
passkey = ["dep:base64", "dep:openssl", "dep:serde_json"]
setup = ["dep:semver", "dep:reqwest", "docs", "audit", "smartcard", "logging"]
smartcard = ["dep:card-backend-pcsc", "dep:openpgp-card"]

[dependencies]
thiserror = "2.0"
adw = { version = "0.9.2", package = "libadwaita", features = ["gtk_v4_18", "v1_8"] }
walkdir = "2.5.0"
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
ripasso = "0.8.0"
sequoia-openpgp = "2.4.1"
dirs-next = "2.0.0"
shellexpand = "3.1.2"
totp-rs = "6.0.0"
rand = "0.10.2"
regex = "1.13.1"
zeroize = { version = "1.9.0", features = [ "alloc" ] }
secrecy = "0.10.3"
pulldown-cmark = { version = "0.13.4", optional = true }
fido2-rs = { version = "0.5.0", optional = true }
base64 = { version = "0.23.1", optional = true }
hmac = { version = "0.13.0", optional = true }
openssl = { version = "0.10.81", optional = true }
sha2 = "0.11.0"
url = "2.5.8"
qrcode = { version = "0.14.1", default-features = false }
serde_json = { version = "1.0.151", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
anyhow = "1.0"
libc = "0.2"
shlex = "2.0.1"
card-backend-pcsc = { version = "0.5.2", optional = true }
libfido2-sys = { version = "0.5.1", optional = true }
openpgp-card = { version = "0.7.0", optional = true }
semver = { version = "1.0.28", optional = true }
reqwest = { version = "0.13.4", optional = true, default-features = false, features = ["blocking", "json", "rustls"] }

[build-dependencies]
glib-build-tools = "0.22.8"

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = "0.1.31"

[target.'cfg(target_os = "windows")'.dependencies]
semver = "1.0.28"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "rustls"] }
winsafe = { version = "0.0.28", features = ["shell"] }
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }
