name: Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-26.04
            target: x86_64-unknown-linux-gnu
            appimage_arch: x86_64
          - os: ubuntu-26.04-arm
            target: aarch64-unknown-linux-gnu
            appimage_arch: aarch64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    env:
      APP_ID: io.github.noobping.keycord
      CARGO_TERM_COLOR: always
      BIN_NAME: keycord

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Version
        id: tag
        shell: bash
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "TAG_NAME=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          else
            latest_tag=$(git describe --tags --abbrev=0)
            echo "TAG_NAME=$latest_tag" >> "$GITHUB_ENV"
          fi

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            cargo \
            cmake \
            clang \
            capnproto \
            gcc \
            gettext \
            libadwaita-1-dev \
            libcbor-dev \
            libcairo2-dev \
            libgdk-pixbuf2.0-dev \
            libfido2-dev \
            libglib2.0-dev \
            libgpg-error-dev \
            libgtk-4-dev \
            libhidapi-dev \
            libgpgme-dev \
            libcapnp-dev \
            libpcsclite-dev \
            libpango1.0-dev \
            libssl-dev \
            make \
            mold \
            nettle-dev \
            pkg-config \
            pkgconf
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Verify passkey feature build
        run: cargo test --package keycord --locked --no-run --no-default-features --features passkey

      - name: Build
        run: cargo build --package keycord --locked --release --features setup

      - name: Collect
        if: ${{ env.TAG_NAME != '' }}
        shell: bash
        run: |
          set -euo pipefail
          out="${BIN_NAME}-${TAG_NAME}.${{ matrix.appimage_arch }}"
          mv target/release/keycord "$out"
          echo "FILE=$out" >> "$GITHUB_ENV"

      - name: Release
        if: ${{ env.TAG_NAME != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.FILE }}
